-- ============================================================
-- SIPO — Seed completo de municipios de Colombia
-- ============================================================
-- La tabla municipios tiene UNIQUE en `nombre` (no en codigo_dane).
-- Problema: varios nombres existen en múltiples departamentos
-- (ej: Armenia en Antioquia y Quindío). Se usa DISTINCT ON para
-- quedarnos con UN registro por nombre (orden alfabético por dpto).
-- reteica_pct: % ICA. Capitales principales con tasa conocida;
-- municipios sin dato usan 0.5 (5‰ — promedio nacional construcción).
-- Idempotente: re-ejecutar solo actualiza departamento y tasa.
-- ============================================================

WITH source(nombre, departamento, reteica_pct) AS (VALUES
  -- ── Amazonas ──────────────────────────────────────────────────────────
  ('Leticia'::text,                        'Amazonas'::text,                0.5::numeric),
  ('Puerto Nariño',                        'Amazonas',                      0.5),

  -- ── Antioquia ─────────────────────────────────────────────────────────
  ('Medellín',                             'Antioquia',                     0.6),
  ('Abejorral',                            'Antioquia',                     0.5),
  ('Abriaquí',                             'Antioquia',                     0.5),
  ('Alejandría',                           'Antioquia',                     0.5),
  ('Amagá',                                'Antioquia',                     0.5),
  ('Amalfi',                               'Antioquia',                     0.5),
  ('Andes',                                'Antioquia',                     0.5),
  ('Angelópolis',                          'Antioquia',                     0.5),
  ('Angostura',                            'Antioquia',                     0.5),
  ('Anorí',                                'Antioquia',                     0.5),
  ('Anzá',                                 'Antioquia',                     0.5),
  ('Apartadó',                             'Antioquia',                     0.5),
  ('Arboletes',                            'Antioquia',                     0.5),
  ('Armenia (Antioquia)',                  'Antioquia',                     0.5),
  ('Barbosa',                              'Antioquia',                     0.5),
  ('Bello',                                'Antioquia',                     0.5),
  ('Betania',                              'Antioquia',                     0.5),
  ('Betulia (Antioquia)',                  'Antioquia',                     0.5),
  ('Briceño (Antioquia)',                  'Antioquia',                     0.5),
  ('Buriticá',                             'Antioquia',                     0.5),
  ('Cáceres',                              'Antioquia',                     0.5),
  ('Caicedo',                              'Antioquia',                     0.5),
  ('Caldas (Antioquia)',                   'Antioquia',                     0.5),
  ('Campamento',                           'Antioquia',                     0.5),
  ('Cañasgordas',                          'Antioquia',                     0.5),
  ('Caracolí',                             'Antioquia',                     0.5),
  ('Caramanta',                            'Antioquia',                     0.5),
  ('Carepa',                               'Antioquia',                     0.5),
  ('Carolina del Príncipe',               'Antioquia',                     0.5),
  ('Caucasia',                             'Antioquia',                     0.5),
  ('Chigorodó',                            'Antioquia',                     0.5),
  ('Cisneros',                             'Antioquia',                     0.5),
  ('Ciudad Bolívar',                       'Antioquia',                     0.5),
  ('Cocorná',                              'Antioquia',                     0.5),
  ('Concepción (Antioquia)',               'Antioquia',                     0.5),
  ('Concordia (Antioquia)',                'Antioquia',                     0.5),
  ('Copacabana',                           'Antioquia',                     0.5),
  ('Dabeiba',                              'Antioquia',                     0.5),
  ('Don Matías',                           'Antioquia',                     0.5),
  ('Ebéjico',                              'Antioquia',                     0.5),
  ('El Bagre',                             'Antioquia',                     0.5),
  ('El Carmen de Viboral',                 'Antioquia',                     0.5),
  ('El Santuario',                         'Antioquia',                     0.5),
  ('Entrerríos',                           'Antioquia',                     0.5),
  ('Envigado',                             'Antioquia',                     0.5),
  ('Fredonia',                             'Antioquia',                     0.5),
  ('Frontino',                             'Antioquia',                     0.5),
  ('Giraldo',                              'Antioquia',                     0.5),
  ('Girardota',                            'Antioquia',                     0.5),
  ('Gómez Plata',                          'Antioquia',                     0.5),
  ('Guarne',                               'Antioquia',                     0.5),
  ('Guatapé',                              'Antioquia',                     0.5),
  ('Heliconia',                            'Antioquia',                     0.5),
  ('Hispania',                             'Antioquia',                     0.5),
  ('Itagüí',                               'Antioquia',                     0.5),
  ('Ituango',                              'Antioquia',                     0.5),
  ('Jardín',                               'Antioquia',                     0.5),
  ('Jericó (Antioquia)',                   'Antioquia',                     0.5),
  ('La Ceja',                              'Antioquia',                     0.5),
  ('La Estrella',                          'Antioquia',                     0.5),
  ('La Pintada',                           'Antioquia',                     0.5),
  ('La Unión (Antioquia)',                 'Antioquia',                     0.5),
  ('Liborina',                             'Antioquia',                     0.5),
  ('Maceo',                                'Antioquia',                     0.5),
  ('Marinilla',                            'Antioquia',                     0.5),
  ('Montebello',                           'Antioquia',                     0.5),
  ('Murindó',                              'Antioquia',                     0.5),
  ('Mutatá',                               'Antioquia',                     0.5),
  ('Nariño (Antioquia)',                   'Antioquia',                     0.5),
  ('Nechí',                                'Antioquia',                     0.5),
  ('Necoclí',                              'Antioquia',                     0.5),
  ('Olaya',                                'Antioquia',                     0.5),
  ('El Peñol',                             'Antioquia',                     0.5),
  ('Peque',                                'Antioquia',                     0.5),
  ('Pueblorrico',                          'Antioquia',                     0.5),
  ('Puerto Berrío',                        'Antioquia',                     0.5),
  ('Puerto Nare',                          'Antioquia',                     0.5),
  ('Puerto Triunfo',                       'Antioquia',                     0.5),
  ('Remedios',                             'Antioquia',                     0.5),
  ('Retiro',                               'Antioquia',                     0.5),
  ('Rionegro (Antioquia)',                 'Antioquia',                     0.5),
  ('Sabanalarga (Antioquia)',              'Antioquia',                     0.5),
  ('Sabaneta',                             'Antioquia',                     0.5),
  ('Salgar',                               'Antioquia',                     0.5),
  ('San Andrés de Cuerquia',               'Antioquia',                     0.5),
  ('San Carlos (Antioquia)',               'Antioquia',                     0.5),
  ('San Francisco (Antioquia)',            'Antioquia',                     0.5),
  ('San Jerónimo',                         'Antioquia',                     0.5),
  ('San José de la Montaña',               'Antioquia',                     0.5),
  ('San Juan de Urabá',                    'Antioquia',                     0.5),
  ('San Luis (Antioquia)',                 'Antioquia',                     0.5),
  ('San Pedro de los Milagros',            'Antioquia',                     0.5),
  ('San Pedro de Urabá',                   'Antioquia',                     0.5),
  ('San Rafael',                           'Antioquia',                     0.5),
  ('San Roque',                            'Antioquia',                     0.5),
  ('San Vicente Ferrer',                   'Antioquia',                     0.5),
  ('Santa Bárbara (Antioquia)',            'Antioquia',                     0.5),
  ('Santa Rosa de Osos',                   'Antioquia',                     0.5),
  ('Santo Domingo',                        'Antioquia',                     0.5),
  ('Segovia',                              'Antioquia',                     0.5),
  ('Sonsón',                               'Antioquia',                     0.5),
  ('Sopetrán',                             'Antioquia',                     0.5),
  ('Támesis',                              'Antioquia',                     0.5),
  ('Tarazá',                               'Antioquia',                     0.5),
  ('Tarso',                                'Antioquia',                     0.5),
  ('Titiribí',                             'Antioquia',                     0.5),
  ('Toledo (Antioquia)',                   'Antioquia',                     0.5),
  ('Turbo',                                'Antioquia',                     0.5),
  ('Uramita',                              'Antioquia',                     0.5),
  ('Urrao',                                'Antioquia',                     0.5),
  ('Valdivia',                             'Antioquia',                     0.5),
  ('Valparaíso (Antioquia)',               'Antioquia',                     0.5),
  ('Vegachí',                              'Antioquia',                     0.5),
  ('Venecia (Antioquia)',                  'Antioquia',                     0.5),
  ('Vigía del Fuerte',                     'Antioquia',                     0.5),
  ('Yalí',                                 'Antioquia',                     0.5),
  ('Yarumal',                              'Antioquia',                     0.5),
  ('Yolombó',                              'Antioquia',                     0.5),
  ('Yondó',                                'Antioquia',                     0.5),
  ('Zaragoza',                             'Antioquia',                     0.5),

  -- ── Arauca ────────────────────────────────────────────────────────────
  ('Arauca',                               'Arauca',                        0.5),
  ('Arauquita',                            'Arauca',                        0.5),
  ('Cravo Norte',                          'Arauca',                        0.5),
  ('Fortul',                               'Arauca',                        0.5),
  ('Puerto Rondón',                        'Arauca',                        0.5),
  ('Saravena',                             'Arauca',                        0.5),
  ('Tame',                                 'Arauca',                        0.5),

  -- ── Atlántico ─────────────────────────────────────────────────────────
  ('Barranquilla',                         'Atlántico',                     0.5),
  ('Baranoa',                              'Atlántico',                     0.5),
  ('Campo de la Cruz',                     'Atlántico',                     0.5),
  ('Candelaria (Atlántico)',               'Atlántico',                     0.5),
  ('Galapa',                               'Atlántico',                     0.5),
  ('Juan de Acosta',                       'Atlántico',                     0.5),
  ('Luruaco',                              'Atlántico',                     0.5),
  ('Malambo',                              'Atlántico',                     0.5),
  ('Manatí',                               'Atlántico',                     0.5),
  ('Palmar de Varela',                     'Atlántico',                     0.5),
  ('Piojó',                                'Atlántico',                     0.5),
  ('Polonuevo',                            'Atlántico',                     0.5),
  ('Ponedera',                             'Atlántico',                     0.5),
  ('Puerto Colombia',                      'Atlántico',                     0.5),
  ('Repelón',                              'Atlántico',                     0.5),
  ('Sabanagrande',                         'Atlántico',                     0.5),
  ('Sabanalarga',                          'Atlántico',                     0.5),
  ('Santa Lucía',                          'Atlántico',                     0.5),
  ('Santo Tomás',                          'Atlántico',                     0.5),
  ('Soledad',                              'Atlántico',                     0.5),
  ('Suán',                                 'Atlántico',                     0.5),
  ('Tubará',                               'Atlántico',                     0.5),
  ('Usiacurí',                             'Atlántico',                     0.5),

  -- ── Bogotá D.C. ───────────────────────────────────────────────────────
  ('Bogotá D.C.',                          'Bogotá D.C.',                   0.414),

  -- ── Bolívar ───────────────────────────────────────────────────────────
  ('Cartagena',                            'Bolívar',                       0.5),
  ('Achí',                                 'Bolívar',                       0.5),
  ('Altos del Rosario',                    'Bolívar',                       0.5),
  ('Arenal (Bolívar)',                      'Bolívar',                       0.5),
  ('Arjona',                               'Bolívar',                       0.5),
  ('Arroyohondo',                          'Bolívar',                       0.5),
  ('Barranco de Loba',                     'Bolívar',                       0.5),
  ('Calamar (Bolívar)',                    'Bolívar',                       0.5),
  ('Cantagallo',                           'Bolívar',                       0.5),
  ('Cicuco',                               'Bolívar',                       0.5),
  ('Clemencia',                            'Bolívar',                       0.5),
  ('Córdoba (Bolívar)',                    'Bolívar',                       0.5),
  ('El Carmen de Bolívar',                 'Bolívar',                       0.5),
  ('El Guamo (Bolívar)',                   'Bolívar',                       0.5),
  ('El Peñón (Bolívar)',                   'Bolívar',                       0.5),
  ('Hatillo de Loba',                      'Bolívar',                       0.5),
  ('Magangué',                             'Bolívar',                       0.5),
  ('Mahates',                              'Bolívar',                       0.5),
  ('Margarita (Bolívar)',                  'Bolívar',                       0.5),
  ('María la Baja',                        'Bolívar',                       0.5),
  ('Montecristo',                          'Bolívar',                       0.5),
  ('Mompox',                               'Bolívar',                       0.5),
  ('Morales (Bolívar)',                    'Bolívar',                       0.5),
  ('Norosí',                               'Bolívar',                       0.5),
  ('Pinillos',                             'Bolívar',                       0.5),
  ('Regidor',                              'Bolívar',                       0.5),
  ('Río Viejo',                            'Bolívar',                       0.5),
  ('San Cristóbal (Bolívar)',              'Bolívar',                       0.5),
  ('San Estanislao',                       'Bolívar',                       0.5),
  ('San Fernando (Bolívar)',               'Bolívar',                       0.5),
  ('San Jacinto',                          'Bolívar',                       0.5),
  ('San Jacinto del Cauca',               'Bolívar',                       0.5),
  ('San Juan Nepomuceno',                  'Bolívar',                       0.5),
  ('San Martín de Loba',                   'Bolívar',                       0.5),
  ('San Pablo (Bolívar)',                  'Bolívar',                       0.5),
  ('Santa Catalina',                       'Bolívar',                       0.5),
  ('Santa Rosa (Bolívar)',                 'Bolívar',                       0.5),
  ('Santa Rosa del Sur',                   'Bolívar',                       0.5),
  ('Simití',                               'Bolívar',                       0.5),
  ('Soplaviento',                          'Bolívar',                       0.5),
  ('Talaigua Nuevo',                       'Bolívar',                       0.5),
  ('Tiquisio',                             'Bolívar',                       0.5),
  ('Turbaco',                              'Bolívar',                       0.5),
  ('Turbaná',                              'Bolívar',                       0.5),
  ('Villanueva (Bolívar)',                 'Bolívar',                       0.5),
  ('Zambrano',                             'Bolívar',                       0.5),

  -- ── Boyacá ────────────────────────────────────────────────────────────
  ('Tunja',                                'Boyacá',                        0.5),
  ('Almeida',                              'Boyacá',                        0.5),
  ('Aquitania',                            'Boyacá',                        0.5),
  ('Arcabuco',                             'Boyacá',                        0.5),
  ('Belén (Boyacá)',                       'Boyacá',                        0.5),
  ('Berbeo',                               'Boyacá',                        0.5),
  ('Betéitiva',                            'Boyacá',                        0.5),
  ('Boavita',                              'Boyacá',                        0.5),
  ('Boyacá',                               'Boyacá',                        0.5),
  ('Briceño (Boyacá)',                     'Boyacá',                        0.5),
  ('Buenavista (Boyacá)',                  'Boyacá',                        0.5),
  ('Busbanzá',                             'Boyacá',                        0.5),
  ('Caldas (Boyacá)',                      'Boyacá',                        0.5),
  ('Campohermoso',                         'Boyacá',                        0.5),
  ('Cerinza',                              'Boyacá',                        0.5),
  ('Chinavita',                            'Boyacá',                        0.5),
  ('Chiquinquirá',                         'Boyacá',                        0.5),
  ('Chíquiza',                             'Boyacá',                        0.5),
  ('Chiscas',                              'Boyacá',                        0.5),
  ('Chita',                                'Boyacá',                        0.5),
  ('Chitaraque',                           'Boyacá',                        0.5),
  ('Chivatá',                              'Boyacá',                        0.5),
  ('Ciénega',                              'Boyacá',                        0.5),
  ('Cómbita',                              'Boyacá',                        0.5),
  ('Coper',                                'Boyacá',                        0.5),
  ('Corrales',                             'Boyacá',                        0.5),
  ('Covarachía',                           'Boyacá',                        0.5),
  ('Cubará',                               'Boyacá',                        0.5),
  ('Cucaita',                              'Boyacá',                        0.5),
  ('Cuítiva',                              'Boyacá',                        0.5),
  ('Duitama',                              'Boyacá',                        0.5),
  ('El Cocuy',                             'Boyacá',                        0.5),
  ('El Espino (Boyacá)',                   'Boyacá',                        0.5),
  ('Firavitoba',                           'Boyacá',                        0.5),
  ('Floresta (Boyacá)',                    'Boyacá',                        0.5),
  ('Gachantivá',                           'Boyacá',                        0.5),
  ('Gámeza',                               'Boyacá',                        0.5),
  ('Garagoa',                              'Boyacá',                        0.5),
  ('Guacamayas',                           'Boyacá',                        0.5),
  ('Guateque',                             'Boyacá',                        0.5),
  ('Guayatá',                              'Boyacá',                        0.5),
  ('Güicán',                               'Boyacá',                        0.5),
  ('Iza',                                  'Boyacá',                        0.5),
  ('Jenesano',                             'Boyacá',                        0.5),
  ('Jericó (Boyacá)',                      'Boyacá',                        0.5),
  ('La Capilla',                           'Boyacá',                        0.5),
  ('La Uvita',                             'Boyacá',                        0.5),
  ('La Victoria (Boyacá)',                 'Boyacá',                        0.5),
  ('Labranzagrande',                       'Boyacá',                        0.5),
  ('Macanal',                              'Boyacá',                        0.5),
  ('Maripí',                               'Boyacá',                        0.5),
  ('Miraflores (Boyacá)',                  'Boyacá',                        0.5),
  ('Mongua',                               'Boyacá',                        0.5),
  ('Monguí',                               'Boyacá',                        0.5),
  ('Moniquirá',                            'Boyacá',                        0.5),
  ('Motavita',                             'Boyacá',                        0.5),
  ('Muzo',                                 'Boyacá',                        0.5),
  ('Nobsa',                                'Boyacá',                        0.5),
  ('Nuevo Colón',                          'Boyacá',                        0.5),
  ('Oicatá',                               'Boyacá',                        0.5),
  ('Otanche',                              'Boyacá',                        0.5),
  ('Pachavita',                            'Boyacá',                        0.5),
  ('Páez (Boyacá)',                        'Boyacá',                        0.5),
  ('Paipa',                                'Boyacá',                        0.5),
  ('Pajarito',                             'Boyacá',                        0.5),
  ('Panqueba',                             'Boyacá',                        0.5),
  ('Pauna',                                'Boyacá',                        0.5),
  ('Paya',                                 'Boyacá',                        0.5),
  ('Paz de Río',                           'Boyacá',                        0.5),
  ('Pesca',                                'Boyacá',                        0.5),
  ('Pisba',                                'Boyacá',                        0.5),
  ('Puerto Boyacá',                        'Boyacá',                        0.5),
  ('Quípama',                              'Boyacá',                        0.5),
  ('Ramiriquí',                            'Boyacá',                        0.5),
  ('Ráquira',                              'Boyacá',                        0.5),
  ('Rondón',                               'Boyacá',                        0.5),
  ('Saboyá',                               'Boyacá',                        0.5),
  ('Sáchica',                              'Boyacá',                        0.5),
  ('Samacá',                               'Boyacá',                        0.5),
  ('San Eduardo',                          'Boyacá',                        0.5),
  ('San José de Pare',                     'Boyacá',                        0.5),
  ('San Luis de Gaceno',                   'Boyacá',                        0.5),
  ('San Mateo (Boyacá)',                   'Boyacá',                        0.5),
  ('San Miguel de Sema',                   'Boyacá',                        0.5),
  ('San Pablo de Borbur',                  'Boyacá',                        0.5),
  ('Santa María (Boyacá)',                 'Boyacá',                        0.5),
  ('Santa Rosa de Viterbo',               'Boyacá',                        0.5),
  ('Santa Sofía (Boyacá)',                'Boyacá',                        0.5),
  ('Sativanorte',                          'Boyacá',                        0.5),
  ('Sativasur',                            'Boyacá',                        0.5),
  ('Siachoque',                            'Boyacá',                        0.5),
  ('Soatá',                                'Boyacá',                        0.5),
  ('Socotá',                               'Boyacá',                        0.5),
  ('Socha',                                'Boyacá',                        0.5),
  ('Sogamoso',                             'Boyacá',                        0.5),
  ('Somondoco',                            'Boyacá',                        0.5),
  ('Sora',                                 'Boyacá',                        0.5),
  ('Soracá',                               'Boyacá',                        0.5),
  ('Sotaquirá',                            'Boyacá',                        0.5),
  ('Susacón',                              'Boyacá',                        0.5),
  ('Sutamarchán',                          'Boyacá',                        0.5),
  ('Sutatenza',                            'Boyacá',                        0.5),
  ('Tasco',                                'Boyacá',                        0.5),
  ('Tenza',                                'Boyacá',                        0.5),
  ('Tibaná',                               'Boyacá',                        0.5),
  ('Tibasosa',                             'Boyacá',                        0.5),
  ('Tinjacá',                              'Boyacá',                        0.5),
  ('Tipacoque',                            'Boyacá',                        0.5),
  ('Toca',                                 'Boyacá',                        0.5),
  ('Togüí',                                'Boyacá',                        0.5),
  ('Tópaga',                               'Boyacá',                        0.5),
  ('Tota',                                 'Boyacá',                        0.5),
  ('Turmequé',                             'Boyacá',                        0.5),
  ('Tuta',                                 'Boyacá',                        0.5),
  ('Tutazá',                               'Boyacá',                        0.5),
  ('Umbita',                               'Boyacá',                        0.5),
  ('Ventaquemada',                         'Boyacá',                        0.5),
  ('Villa de Leyva',                       'Boyacá',                        0.5),
  ('Viracachá',                            'Boyacá',                        0.5),
  ('Zetaquira',                            'Boyacá',                        0.5),

  -- ── Caldas ────────────────────────────────────────────────────────────
  ('Manizales',                            'Caldas',                        0.5),
  ('Aguadas',                              'Caldas',                        0.5),
  ('Anserma',                              'Caldas',                        0.5),
  ('Aranzazu',                             'Caldas',                        0.5),
  ('Belalcázar',                           'Caldas',                        0.5),
  ('Chinchiná',                            'Caldas',                        0.5),
  ('Filadelfia',                           'Caldas',                        0.5),
  ('La Dorada',                            'Caldas',                        0.5),
  ('La Merced',                            'Caldas',                        0.5),
  ('Manzanares',                           'Caldas',                        0.5),
  ('Marmato',                              'Caldas',                        0.5),
  ('Marquetalia',                          'Caldas',                        0.5),
  ('Marulanda',                            'Caldas',                        0.5),
  ('Neira',                                'Caldas',                        0.5),
  ('Norcasia',                             'Caldas',                        0.5),
  ('Pácora',                               'Caldas',                        0.5),
  ('Palestina (Caldas)',                   'Caldas',                        0.5),
  ('Pensilvania',                          'Caldas',                        0.5),
  ('Riosucio (Caldas)',                    'Caldas',                        0.5),
  ('Risaralda (Caldas)',                   'Caldas',                        0.5),
  ('Salamina (Caldas)',                    'Caldas',                        0.5),
  ('Samaná',                               'Caldas',                        0.5),
  ('San José (Caldas)',                    'Caldas',                        0.5),
  ('Supía',                                'Caldas',                        0.5),
  ('Victoria (Caldas)',                    'Caldas',                        0.5),
  ('Villamaría',                           'Caldas',                        0.5),
  ('Viterbo',                              'Caldas',                        0.5),

  -- ── Caquetá ───────────────────────────────────────────────────────────
  ('Florencia',                            'Caquetá',                       0.5),
  ('Albania (Caquetá)',                    'Caquetá',                       0.5),
  ('Belén de los Andaquíes',              'Caquetá',                       0.5),
  ('Cartagena del Chairá',                'Caquetá',                       0.5),
  ('Curillo',                              'Caquetá',                       0.5),
  ('El Doncello',                          'Caquetá',                       0.5),
  ('El Paujil',                            'Caquetá',                       0.5),
  ('La Montañita',                        'Caquetá',                       0.5),
  ('Milán (Caquetá)',                     'Caquetá',                       0.5),
  ('Morelia (Caquetá)',                   'Caquetá',                       0.5),
  ('Puerto Rico (Caquetá)',               'Caquetá',                       0.5),
  ('San José del Fragua',                 'Caquetá',                       0.5),
  ('San Vicente del Caguán',              'Caquetá',                       0.5),
  ('Solano',                               'Caquetá',                       0.5),
  ('Solita',                               'Caquetá',                       0.5),
  ('Valparaíso (Caquetá)',               'Caquetá',                       0.5),

  -- ── Casanare ──────────────────────────────────────────────────────────
  ('Yopal',                                'Casanare',                      0.5),
  ('Aguazul',                              'Casanare',                      0.5),
  ('Chámeza',                              'Casanare',                      0.5),
  ('Hato Corozal',                         'Casanare',                      0.5),
  ('La Salina',                            'Casanare',                      0.5),
  ('Maní',                                 'Casanare',                      0.5),
  ('Monterrey (Casanare)',                 'Casanare',                      0.5),
  ('Nunchía',                              'Casanare',                      0.5),
  ('Orocué',                               'Casanare',                      0.5),
  ('Paz de Ariporo',                       'Casanare',                      0.5),
  ('Pore',                                 'Casanare',                      0.5),
  ('Recetor',                              'Casanare',                      0.5),
  ('Sabanalarga (Casanare)',               'Casanare',                      0.5),
  ('Sácama',                               'Casanare',                      0.5),
  ('San Luis de Palenque',                'Casanare',                      0.5),
  ('Támara',                               'Casanare',                      0.5),
  ('Tauramena',                            'Casanare',                      0.5),
  ('Trinidad (Casanare)',                  'Casanare',                      0.5),
  ('Villanueva (Casanare)',                'Casanare',                      0.5),

  -- ── Cauca ─────────────────────────────────────────────────────────────
  ('Popayán',                              'Cauca',                         0.5),
  ('Almaguer',                             'Cauca',                         0.5),
  ('Argelia (Cauca)',                      'Cauca',                         0.5),
  ('Balboa (Cauca)',                       'Cauca',                         0.5),
  ('Bolívar (Cauca)',                      'Cauca',                         0.5),
  ('Buenos Aires (Cauca)',                 'Cauca',                         0.5),
  ('Cajibío',                              'Cauca',                         0.5),
  ('Caldono',                              'Cauca',                         0.5),
  ('Caloto',                               'Cauca',                         0.5),
  ('Corinto',                              'Cauca',                         0.5),
  ('El Tambo (Cauca)',                     'Cauca',                         0.5),
  ('Florencia (Cauca)',                    'Cauca',                         0.5),
  ('Guachené',                             'Cauca',                         0.5),
  ('Guapi',                                'Cauca',                         0.5),
  ('Inzá',                                 'Cauca',                         0.5),
  ('Jambaló',                              'Cauca',                         0.5),
  ('La Sierra (Cauca)',                    'Cauca',                         0.5),
  ('La Vega (Cauca)',                      'Cauca',                         0.5),
  ('López de Micay',                       'Cauca',                         0.5),
  ('Mercaderes',                           'Cauca',                         0.5),
  ('Miranda (Cauca)',                      'Cauca',                         0.5),
  ('Morales (Cauca)',                      'Cauca',                         0.5),
  ('Padilla',                              'Cauca',                         0.5),
  ('Páez (Cauca)',                         'Cauca',                         0.5),
  ('Patía',                                'Cauca',                         0.5),
  ('Piamonte',                             'Cauca',                         0.5),
  ('Piendamó',                             'Cauca',                         0.5),
  ('Puerto Tejada',                        'Cauca',                         0.5),
  ('Puracé',                               'Cauca',                         0.5),
  ('Rosas',                                'Cauca',                         0.5),
  ('San Sebastián (Cauca)',               'Cauca',                         0.5),
  ('Santa Rosa (Cauca)',                   'Cauca',                         0.5),
  ('Santander de Quilichao',               'Cauca',                         0.5),
  ('Silvia',                               'Cauca',                         0.5),
  ('Sotara',                               'Cauca',                         0.5),
  ('Suárez (Cauca)',                       'Cauca',                         0.5),
  ('Sucre (Cauca)',                        'Cauca',                         0.5),
  ('Timbío',                               'Cauca',                         0.5),
  ('Timbiquí',                             'Cauca',                         0.5),
  ('Toribío',                              'Cauca',                         0.5),
  ('Totoró',                               'Cauca',                         0.5),
  ('Villa Rica',                           'Cauca',                         0.5),

  -- ── Cesar ─────────────────────────────────────────────────────────────
  ('Valledupar',                           'Cesar',                         0.5),
  ('Aguachica',                            'Cesar',                         0.5),
  ('Agustín Codazzi',                      'Cesar',                         0.5),
  ('Astrea',                               'Cesar',                         0.5),
  ('Becerril',                             'Cesar',                         0.5),
  ('Bosconia',                             'Cesar',                         0.5),
  ('Chimichagua',                          'Cesar',                         0.5),
  ('Chiriguaná',                           'Cesar',                         0.5),
  ('Curumaní',                             'Cesar',                         0.5),
  ('El Copey',                             'Cesar',                         0.5),
  ('El Paso (Cesar)',                      'Cesar',                         0.5),
  ('Gamarra',                              'Cesar',                         0.5),
  ('González (Cesar)',                     'Cesar',                         0.5),
  ('La Gloria (Cesar)',                    'Cesar',                         0.5),
  ('La Jagua de Ibirico',                  'Cesar',                         0.5),
  ('La Paz (Cesar)',                       'Cesar',                         0.5),
  ('Manaure Balcón del Cesar',            'Cesar',                         0.5),
  ('Pailitas',                             'Cesar',                         0.5),
  ('Pelaya',                               'Cesar',                         0.5),
  ('Pueblo Bello',                         'Cesar',                         0.5),
  ('Río de Oro',                           'Cesar',                         0.5),
  ('San Alberto',                          'Cesar',                         0.5),
  ('San Diego (Cesar)',                    'Cesar',                         0.5),
  ('San Martín (Cesar)',                   'Cesar',                         0.5),
  ('Tamalameque',                          'Cesar',                         0.5),

  -- ── Chocó ─────────────────────────────────────────────────────────────
  ('Quibdó',                               'Chocó',                         0.5),
  ('Acandí',                               'Chocó',                         0.5),
  ('Alto Baudó',                           'Chocó',                         0.5),
  ('Atrato',                               'Chocó',                         0.5),
  ('Bagadó',                               'Chocó',                         0.5),
  ('Bahía Solano',                         'Chocó',                         0.5),
  ('Bajo Baudó',                           'Chocó',                         0.5),
  ('Bojayá',                               'Chocó',                         0.5),
  ('Carmen del Darién',                    'Chocó',                         0.5),
  ('Cértegui',                             'Chocó',                         0.5),
  ('Condoto',                              'Chocó',                         0.5),
  ('El Cantón del San Pablo',              'Chocó',                         0.5),
  ('El Carmen de Atrato',                  'Chocó',                         0.5),
  ('El Litoral del San Juan',              'Chocó',                         0.5),
  ('Istmina',                              'Chocó',                         0.5),
  ('Juradó',                               'Chocó',                         0.5),
  ('Lloró',                                'Chocó',                         0.5),
  ('Medio Atrato',                         'Chocó',                         0.5),
  ('Medio Baudó',                          'Chocó',                         0.5),
  ('Medio San Juan',                       'Chocó',                         0.5),
  ('Nóvita',                               'Chocó',                         0.5),
  ('Nuquí',                                'Chocó',                         0.5),
  ('Río Iro',                              'Chocó',                         0.5),
  ('Río Quito',                            'Chocó',                         0.5),
  ('Riosucio (Chocó)',                    'Chocó',                         0.5),
  ('San José del Palmar',                  'Chocó',                         0.5),
  ('Sipí',                                 'Chocó',                         0.5),
  ('Tadó',                                 'Chocó',                         0.5),
  ('Unguía',                               'Chocó',                         0.5),
  ('Unión Panamericana',                   'Chocó',                         0.5),

  -- ── Córdoba ───────────────────────────────────────────────────────────
  ('Montería',                             'Córdoba',                       0.5),
  ('Ayapel',                               'Córdoba',                       0.5),
  ('Buenavista (Córdoba)',                 'Córdoba',                       0.5),
  ('Canalete',                             'Córdoba',                       0.5),
  ('Cereté',                               'Córdoba',                       0.5),
  ('Chimá',                                'Córdoba',                       0.5),
  ('Chinú',                                'Córdoba',                       0.5),
  ('Ciénaga de Oro',                       'Córdoba',                       0.5),
  ('Cotorra',                              'Córdoba',                       0.5),
  ('La Apartada',                          'Córdoba',                       0.5),
  ('Lorica',                               'Córdoba',                       0.5),
  ('Los Córdobas',                         'Córdoba',                       0.5),
  ('Momil',                                'Córdoba',                       0.5),
  ('Montelíbano',                          'Córdoba',                       0.5),
  ('Moñitos',                              'Córdoba',                       0.5),
  ('Planeta Rica',                         'Córdoba',                       0.5),
  ('Pueblo Nuevo (Córdoba)',               'Córdoba',                       0.5),
  ('Puerto Escondido',                     'Córdoba',                       0.5),
  ('Puerto Libertador',                    'Córdoba',                       0.5),
  ('Purísima de la Concepción',           'Córdoba',                       0.5),
  ('Sahagún',                              'Córdoba',                       0.5),
  ('San Andrés de Sotavento',             'Córdoba',                       0.5),
  ('San Antero',                           'Córdoba',                       0.5),
  ('San Bernardo del Viento',              'Córdoba',                       0.5),
  ('San Carlos (Córdoba)',                 'Córdoba',                       0.5),
  ('San José de Uré',                      'Córdoba',                       0.5),
  ('San Pelayo',                           'Córdoba',                       0.5),
  ('Tierralta',                            'Córdoba',                       0.5),
  ('Tuchín',                               'Córdoba',                       0.5),
  ('Valencia',                             'Córdoba',                       0.5),

  -- ── Cundinamarca ──────────────────────────────────────────────────────
  ('Agua de Dios',                         'Cundinamarca',                  0.5),
  ('Albán (Cundinamarca)',                 'Cundinamarca',                  0.5),
  ('Anapoima',                             'Cundinamarca',                  0.5),
  ('Anolaima',                             'Cundinamarca',                  0.5),
  ('Apulo',                                'Cundinamarca',                  0.5),
  ('Arbeláez',                             'Cundinamarca',                  0.5),
  ('Beltrán (Cundinamarca)',               'Cundinamarca',                  0.5),
  ('Bituima',                              'Cundinamarca',                  0.5),
  ('Bojacá',                               'Cundinamarca',                  0.5),
  ('Cabrera (Cundinamarca)',               'Cundinamarca',                  0.5),
  ('Cachipay',                             'Cundinamarca',                  0.5),
  ('Cajicá',                               'Cundinamarca',                  0.5),
  ('Caparrapí',                            'Cundinamarca',                  0.5),
  ('Cáqueza',                              'Cundinamarca',                  0.5),
  ('Carmen de Carupa',                     'Cundinamarca',                  0.5),
  ('Chaguaní',                             'Cundinamarca',                  0.5),
  ('Chía',                                 'Cundinamarca',                  0.5),
  ('Chipaque',                             'Cundinamarca',                  0.5),
  ('Choachí',                              'Cundinamarca',                  0.5),
  ('Chocontá',                             'Cundinamarca',                  0.5),
  ('Cogua',                                'Cundinamarca',                  0.5),
  ('Cota',                                 'Cundinamarca',                  0.5),
  ('Cucunubá',                             'Cundinamarca',                  0.5),
  ('El Colegio',                           'Cundinamarca',                  0.5),
  ('El Peñón (Cundinamarca)',             'Cundinamarca',                  0.5),
  ('El Rosal',                             'Cundinamarca',                  0.5),
  ('Facatativá',                           'Cundinamarca',                  0.5),
  ('Fomeque',                              'Cundinamarca',                  0.5),
  ('Fosca',                                'Cundinamarca',                  0.5),
  ('Funza',                                'Cundinamarca',                  0.5),
  ('Fúquene',                              'Cundinamarca',                  0.5),
  ('Fusagasugá',                           'Cundinamarca',                  0.5),
  ('Gachalá',                              'Cundinamarca',                  0.5),
  ('Gachancipá',                           'Cundinamarca',                  0.5),
  ('Gachetá',                              'Cundinamarca',                  0.5),
  ('Gama',                                 'Cundinamarca',                  0.5),
  ('Girardot',                             'Cundinamarca',                  0.5),
  ('Granada (Cundinamarca)',               'Cundinamarca',                  0.5),
  ('Guachetá',                             'Cundinamarca',                  0.5),
  ('Guaduas',                              'Cundinamarca',                  0.5),
  ('Guasca',                               'Cundinamarca',                  0.5),
  ('Guataquí',                             'Cundinamarca',                  0.5),
  ('Guatavita',                            'Cundinamarca',                  0.5),
  ('Guayabal de Síquima',                 'Cundinamarca',                  0.5),
  ('Guayabetal',                           'Cundinamarca',                  0.5),
  ('Gutiérrez (Cundinamarca)',             'Cundinamarca',                  0.5),
  ('Jerusalén (Cundinamarca)',             'Cundinamarca',                  0.5),
  ('Junín (Cundinamarca)',                 'Cundinamarca',                  0.5),
  ('La Calera',                            'Cundinamarca',                  0.5),
  ('La Mesa',                              'Cundinamarca',                  0.5),
  ('La Palma',                             'Cundinamarca',                  0.5),
  ('La Peña',                              'Cundinamarca',                  0.5),
  ('La Vega',                              'Cundinamarca',                  0.5),
  ('Lenguazaque',                          'Cundinamarca',                  0.5),
  ('Macheta',                              'Cundinamarca',                  0.5),
  ('Madrid',                               'Cundinamarca',                  0.5),
  ('Manta (Cundinamarca)',                 'Cundinamarca',                  0.5),
  ('Medina (Cundinamarca)',                'Cundinamarca',                  0.5),
  ('Mosquera (Cundinamarca)',              'Cundinamarca',                  0.5),
  ('Nariño (Cundinamarca)',                'Cundinamarca',                  0.5),
  ('Nemocón',                              'Cundinamarca',                  0.5),
  ('Nilo',                                 'Cundinamarca',                  0.5),
  ('Nimaima',                              'Cundinamarca',                  0.5),
  ('Nocaima',                              'Cundinamarca',                  0.5),
  ('Pacho',                                'Cundinamarca',                  0.5),
  ('Paime',                                'Cundinamarca',                  0.5),
  ('Pandi',                                'Cundinamarca',                  0.5),
  ('Paratebueno',                          'Cundinamarca',                  0.5),
  ('Pasca',                                'Cundinamarca',                  0.5),
  ('Puerto Salgar',                        'Cundinamarca',                  0.5),
  ('Pulí',                                 'Cundinamarca',                  0.5),
  ('Quebradanegra',                        'Cundinamarca',                  0.5),
  ('Quetame',                              'Cundinamarca',                  0.5),
  ('Quipile',                              'Cundinamarca',                  0.5),
  ('Ricaurte (Cundinamarca)',              'Cundinamarca',                  0.5),
  ('San Antonio del Tequendama',           'Cundinamarca',                  0.5),
  ('San Bernardo (Cundinamarca)',          'Cundinamarca',                  0.5),
  ('San Cayetano (Cundinamarca)',          'Cundinamarca',                  0.5),
  ('San Francisco (Cundinamarca)',         'Cundinamarca',                  0.5),
  ('San Juan de Río Seco',                'Cundinamarca',                  0.5),
  ('Sasaima',                              'Cundinamarca',                  0.5),
  ('Sesquilé',                             'Cundinamarca',                  0.5),
  ('Sibaté',                               'Cundinamarca',                  0.5),
  ('Silvania',                             'Cundinamarca',                  0.5),
  ('Simijaca',                             'Cundinamarca',                  0.5),
  ('Soacha',                               'Cundinamarca',                  0.5),
  ('Sopó',                                 'Cundinamarca',                  0.5),
  ('Subachoque',                           'Cundinamarca',                  0.5),
  ('Suesca',                               'Cundinamarca',                  0.5),
  ('Supatá',                               'Cundinamarca',                  0.5),
  ('Susa',                                 'Cundinamarca',                  0.5),
  ('Sutatausa',                            'Cundinamarca',                  0.5),
  ('Tabio',                                'Cundinamarca',                  0.5),
  ('Tausa',                                'Cundinamarca',                  0.5),
  ('Tena (Cundinamarca)',                  'Cundinamarca',                  0.5),
  ('Tenjo',                                'Cundinamarca',                  0.5),
  ('Tibacuy',                              'Cundinamarca',                  0.5),
  ('Tibirita',                             'Cundinamarca',                  0.5),
  ('Tocaima',                              'Cundinamarca',                  0.5),
  ('Tocancipá',                            'Cundinamarca',                  0.5),
  ('Topaipí',                              'Cundinamarca',                  0.5),
  ('Ubalá',                                'Cundinamarca',                  0.5),
  ('Ubaque',                               'Cundinamarca',                  0.5),
  ('Une',                                  'Cundinamarca',                  0.5),
  ('Uticá',                                'Cundinamarca',                  0.5),
  ('Vergara',                              'Cundinamarca',                  0.5),
  ('Vianí',                                'Cundinamarca',                  0.5),
  ('Villagómez',                           'Cundinamarca',                  0.5),
  ('Villapinzón',                          'Cundinamarca',                  0.5),
  ('Villeta',                              'Cundinamarca',                  0.5),
  ('Viotá',                                'Cundinamarca',                  0.5),
  ('Yacopí',                               'Cundinamarca',                  0.5),
  ('Zipacón',                              'Cundinamarca',                  0.5),
  ('Zipaquirá',                            'Cundinamarca',                  0.5),

  -- ── Guainía ───────────────────────────────────────────────────────────
  ('Inírida',                              'Guainía',                       0.5),

  -- ── Guaviare ──────────────────────────────────────────────────────────
  ('San José del Guaviare',               'Guaviare',                      0.5),
  ('Calamar (Guaviare)',                   'Guaviare',                      0.5),
  ('El Retorno',                           'Guaviare',                      0.5),
  ('Miraflores (Guaviare)',                'Guaviare',                      0.5),

  -- ── Huila ─────────────────────────────────────────────────────────────
  ('Neiva',                                'Huila',                         0.5),
  ('Acevedo',                              'Huila',                         0.5),
  ('Agrado',                               'Huila',                         0.5),
  ('Aipe',                                 'Huila',                         0.5),
  ('Algeciras',                            'Huila',                         0.5),
  ('Altamira',                             'Huila',                         0.5),
  ('Baraya',                               'Huila',                         0.5),
  ('Campoalegre',                          'Huila',                         0.5),
  ('Colombia (Huila)',                     'Huila',                         0.5),
  ('Elías',                                'Huila',                         0.5),
  ('Garzón',                               'Huila',                         0.5),
  ('Gigante',                              'Huila',                         0.5),
  ('Guadalupe (Huila)',                    'Huila',                         0.5),
  ('Hobo',                                 'Huila',                         0.5),
  ('Iquira',                               'Huila',                         0.5),
  ('Isnos',                                'Huila',                         0.5),
  ('La Argentina',                         'Huila',                         0.5),
  ('La Plata (Huila)',                     'Huila',                         0.5),
  ('Nátaga',                               'Huila',                         0.5),
  ('Oporapa',                              'Huila',                         0.5),
  ('Paicol',                               'Huila',                         0.5),
  ('Palermo (Huila)',                      'Huila',                         0.5),
  ('Palestina (Huila)',                    'Huila',                         0.5),
  ('Pital',                                'Huila',                         0.5),
  ('Pitalito',                             'Huila',                         0.5),
  ('Rivera',                               'Huila',                         0.5),
  ('Saladoblanco',                         'Huila',                         0.5),
  ('San Agustín',                          'Huila',                         0.5),
  ('Santa María (Huila)',                  'Huila',                         0.5),
  ('Suaza',                                'Huila',                         0.5),
  ('Tarqui',                               'Huila',                         0.5),
  ('Tello',                                'Huila',                         0.5),
  ('Teruel',                               'Huila',                         0.5),
  ('Tesalia',                              'Huila',                         0.5),
  ('Timaná',                               'Huila',                         0.5),
  ('Villavieja',                           'Huila',                         0.5),
  ('Yaguará',                              'Huila',                         0.5),

  -- ── La Guajira ────────────────────────────────────────────────────────
  ('Riohacha',                             'La Guajira',                    0.5),
  ('Albania (La Guajira)',                 'La Guajira',                    0.5),
  ('Barrancas',                            'La Guajira',                    0.5),
  ('Dibulla',                              'La Guajira',                    0.5),
  ('Distracción',                          'La Guajira',                    0.5),
  ('El Molino',                            'La Guajira',                    0.5),
  ('Fonseca',                              'La Guajira',                    0.5),
  ('Hatonuevo',                            'La Guajira',                    0.5),
  ('La Jagua del Pilar',                   'La Guajira',                    0.5),
  ('Maicao',                               'La Guajira',                    0.5),
  ('Manaure',                              'La Guajira',                    0.5),
  ('San Juan del Cesar',                   'La Guajira',                    0.5),
  ('Uribia',                               'La Guajira',                    0.5),
  ('Urumita',                              'La Guajira',                    0.5),
  ('Villanueva (La Guajira)',              'La Guajira',                    0.5),

  -- ── Magdalena ─────────────────────────────────────────────────────────
  ('Santa Marta',                          'Magdalena',                     0.5),
  ('Algarrobo',                            'Magdalena',                     0.5),
  ('Aracataca',                            'Magdalena',                     0.5),
  ('Ariguaní',                             'Magdalena',                     0.5),
  ('Cerro de San Antonio',                 'Magdalena',                     0.5),
  ('Chivolo',                              'Magdalena',                     0.5),
  ('Ciénaga',                              'Magdalena',                     0.5),
  ('Concordia (Magdalena)',                'Magdalena',                     0.5),
  ('El Banco',                             'Magdalena',                     0.5),
  ('El Piñón',                             'Magdalena',                     0.5),
  ('El Retén',                             'Magdalena',                     0.5),
  ('Fundación',                            'Magdalena',                     0.5),
  ('Guamal (Magdalena)',                   'Magdalena',                     0.5),
  ('Nueva Granada',                        'Magdalena',                     0.5),
  ('Pedraza',                              'Magdalena',                     0.5),
  ('Pijiño del Carmen',                    'Magdalena',                     0.5),
  ('Pivijay',                              'Magdalena',                     0.5),
  ('Plato',                                'Magdalena',                     0.5),
  ('Pueblo Viejo',                         'Magdalena',                     0.5),
  ('Remolino',                             'Magdalena',                     0.5),
  ('Sabanas de San Ángel',                'Magdalena',                     0.5),
  ('Salamina (Magdalena)',                 'Magdalena',                     0.5),
  ('San Sebastián de Buenavista',          'Magdalena',                     0.5),
  ('San Zenón',                            'Magdalena',                     0.5),
  ('Santa Ana',                            'Magdalena',                     0.5),
  ('Santa Bárbara de Pinto',              'Magdalena',                     0.5),
  ('Sitionuevo',                           'Magdalena',                     0.5),
  ('Tenerife',                             'Magdalena',                     0.5),
  ('Zapayán',                              'Magdalena',                     0.5),
  ('Zona Bananera',                        'Magdalena',                     0.5),

  -- ── Meta ──────────────────────────────────────────────────────────────
  ('Villavicencio',                        'Meta',                          0.5),
  ('Acacías',                              'Meta',                          0.5),
  ('Barranca de Upía',                     'Meta',                          0.5),
  ('Cabuyaro',                             'Meta',                          0.5),
  ('Castilla la Nueva',                    'Meta',                          0.5),
  ('Cubarral',                             'Meta',                          0.5),
  ('Cumaral',                              'Meta',                          0.5),
  ('El Calvario',                          'Meta',                          0.5),
  ('El Castillo',                          'Meta',                          0.5),
  ('El Dorado',                            'Meta',                          0.5),
  ('Fuente de Oro',                        'Meta',                          0.5),
  ('Granada (Meta)',                       'Meta',                          0.5),
  ('Guamal (Meta)',                        'Meta',                          0.5),
  ('La Macarena',                          'Meta',                          0.5),
  ('Lejanías',                             'Meta',                          0.5),
  ('Mapiripán',                            'Meta',                          0.5),
  ('Mesetas',                              'Meta',                          0.5),
  ('La Uribe',                             'Meta',                          0.5),
  ('Puerto Concordia',                     'Meta',                          0.5),
  ('Puerto Gaitán',                        'Meta',                          0.5),
  ('Puerto Lleras',                        'Meta',                          0.5),
  ('Puerto López',                         'Meta',                          0.5),
  ('Puerto Rico (Meta)',                   'Meta',                          0.5),
  ('Restrepo (Meta)',                      'Meta',                          0.5),
  ('San Carlos de Guaroa',                'Meta',                          0.5),
  ('San Juan de Arama',                    'Meta',                          0.5),
  ('San Juanito',                          'Meta',                          0.5),
  ('San Martín (Meta)',                    'Meta',                          0.5),
  ('Vistahermosa',                         'Meta',                          0.5),

  -- ── Nariño ────────────────────────────────────────────────────────────
  ('Pasto',                                'Nariño',                        0.5),
  ('Albán (Nariño)',                       'Nariño',                        0.5),
  ('Aldana',                               'Nariño',                        0.5),
  ('Ancuyá',                               'Nariño',                        0.5),
  ('Arboleda',                             'Nariño',                        0.5),
  ('Barbacoas',                            'Nariño',                        0.5),
  ('Belén (Nariño)',                       'Nariño',                        0.5),
  ('Buesaco',                              'Nariño',                        0.5),
  ('Chachagüí',                            'Nariño',                        0.5),
  ('Colón (Nariño)',                       'Nariño',                        0.5),
  ('Consacá',                              'Nariño',                        0.5),
  ('Contadero',                            'Nariño',                        0.5),
  ('Córdoba (Nariño)',                     'Nariño',                        0.5),
  ('Cuaspud',                              'Nariño',                        0.5),
  ('Cumbal',                               'Nariño',                        0.5),
  ('Cumbitara',                            'Nariño',                        0.5),
  ('El Charco',                            'Nariño',                        0.5),
  ('El Peñol (Nariño)',                    'Nariño',                        0.5),
  ('El Rosario',                           'Nariño',                        0.5),
  ('El Tablón de Gómez',                  'Nariño',                        0.5),
  ('El Tambo (Nariño)',                    'Nariño',                        0.5),
  ('Francisco Pizarro',                    'Nariño',                        0.5),
  ('Funes',                                'Nariño',                        0.5),
  ('Guachucal',                            'Nariño',                        0.5),
  ('Guaitarilla',                          'Nariño',                        0.5),
  ('Gualmatán',                            'Nariño',                        0.5),
  ('Iles',                                 'Nariño',                        0.5),
  ('Imués',                                'Nariño',                        0.5),
  ('Ipiales',                              'Nariño',                        0.5),
  ('La Cruz (Nariño)',                     'Nariño',                        0.5),
  ('La Florida',                           'Nariño',                        0.5),
  ('La Llanada',                           'Nariño',                        0.5),
  ('La Tola',                              'Nariño',                        0.5),
  ('La Unión (Nariño)',                    'Nariño',                        0.5),
  ('Leiva',                                'Nariño',                        0.5),
  ('Linares',                              'Nariño',                        0.5),
  ('Los Andes (Nariño)',                   'Nariño',                        0.5),
  ('Magüí',                                'Nariño',                        0.5),
  ('Mallama',                              'Nariño',                        0.5),
  ('Mosquera (Nariño)',                    'Nariño',                        0.5),
  ('Nariño (Nariño)',                      'Nariño',                        0.5),
  ('Olaya Herrera',                        'Nariño',                        0.5),
  ('Ospina',                               'Nariño',                        0.5),
  ('Policarpa',                            'Nariño',                        0.5),
  ('Potosí',                               'Nariño',                        0.5),
  ('Providencia (Nariño)',                 'Nariño',                        0.5),
  ('Puerres',                              'Nariño',                        0.5),
  ('Pupiales',                             'Nariño',                        0.5),
  ('Ricaurte (Nariño)',                    'Nariño',                        0.5),
  ('Roberto Payán',                        'Nariño',                        0.5),
  ('Samaniego',                            'Nariño',                        0.5),
  ('San Bernardo (Nariño)',               'Nariño',                        0.5),
  ('San Lorenzo (Nariño)',                 'Nariño',                        0.5),
  ('San Pablo (Nariño)',                   'Nariño',                        0.5),
  ('San Pedro de Cartago',                'Nariño',                        0.5),
  ('Sandoná',                              'Nariño',                        0.5),
  ('Santa Bárbara (Nariño)',              'Nariño',                        0.5),
  ('Santacruz',                            'Nariño',                        0.5),
  ('Sapuyes',                              'Nariño',                        0.5),
  ('Taminango',                            'Nariño',                        0.5),
  ('Tangua',                               'Nariño',                        0.5),
  ('Tumaco',                               'Nariño',                        0.5),
  ('Túquerres',                            'Nariño',                        0.5),
  ('Yacuanquer',                           'Nariño',                        0.5),

  -- ── Norte de Santander ────────────────────────────────────────────────
  ('Cúcuta',                               'Norte de Santander',            0.5),
  ('Ábrego',                               'Norte de Santander',            0.5),
  ('Arboledas',                            'Norte de Santander',            0.5),
  ('Bochalema',                            'Norte de Santander',            0.5),
  ('Bucarasica',                           'Norte de Santander',            0.5),
  ('Cachirá',                              'Norte de Santander',            0.5),
  ('Cácota',                               'Norte de Santander',            0.5),
  ('Chinácota',                            'Norte de Santander',            0.5),
  ('Chitagá',                              'Norte de Santander',            0.5),
  ('Convención',                           'Norte de Santander',            0.5),
  ('Cucutilla',                            'Norte de Santander',            0.5),
  ('Durania',                              'Norte de Santander',            0.5),
  ('El Carmen (N. Santander)',             'Norte de Santander',            0.5),
  ('El Tarra',                             'Norte de Santander',            0.5),
  ('El Zulia',                             'Norte de Santander',            0.5),
  ('Gramalote',                            'Norte de Santander',            0.5),
  ('Hacarí',                               'Norte de Santander',            0.5),
  ('Herrán',                               'Norte de Santander',            0.5),
  ('La Esperanza',                         'Norte de Santander',            0.5),
  ('La Playa (N. Santander)',              'Norte de Santander',            0.5),
  ('Labateca',                             'Norte de Santander',            0.5),
  ('Los Patios',                           'Norte de Santander',            0.5),
  ('Lourdes',                              'Norte de Santander',            0.5),
  ('Mutiscua',                             'Norte de Santander',            0.5),
  ('Ocaña',                                'Norte de Santander',            0.5),
  ('Pamplona',                             'Norte de Santander',            0.5),
  ('Pamplonita',                           'Norte de Santander',            0.5),
  ('Puerto Santander',                     'Norte de Santander',            0.5),
  ('Ragonvalia',                           'Norte de Santander',            0.5),
  ('Salazar (N. Santander)',               'Norte de Santander',            0.5),
  ('San Calixto',                          'Norte de Santander',            0.5),
  ('San Cayetano (N. Santander)',          'Norte de Santander',            0.5),
  ('Santiago (N. Santander)',              'Norte de Santander',            0.5),
  ('Sardinata',                            'Norte de Santander',            0.5),
  ('Silos',                                'Norte de Santander',            0.5),
  ('Teorama',                              'Norte de Santander',            0.5),
  ('Tibú',                                 'Norte de Santander',            0.5),
  ('Toledo (N. Santander)',                'Norte de Santander',            0.5),
  ('Villa Caro',                           'Norte de Santander',            0.5),
  ('Villa del Rosario',                    'Norte de Santander',            0.5),

  -- ── Putumayo ──────────────────────────────────────────────────────────
  ('Mocoa',                                'Putumayo',                      0.5),
  ('Colón (Putumayo)',                     'Putumayo',                      0.5),
  ('Orito',                                'Putumayo',                      0.5),
  ('Puerto Asís',                          'Putumayo',                      0.5),
  ('Puerto Caicedo',                       'Putumayo',                      0.5),
  ('Puerto Guzmán',                        'Putumayo',                      0.5),
  ('Puerto Leguízamo',                     'Putumayo',                      0.5),
  ('San Francisco (Putumayo)',             'Putumayo',                      0.5),
  ('San Miguel (Putumayo)',                'Putumayo',                      0.5),
  ('Santiago (Putumayo)',                  'Putumayo',                      0.5),
  ('Sibundoy',                             'Putumayo',                      0.5),
  ('Valle del Guamuez',                    'Putumayo',                      0.5),
  ('Villagarzón',                          'Putumayo',                      0.5),

  -- ── Quindío ───────────────────────────────────────────────────────────
  ('Armenia',                              'Quindío',                       0.5),
  ('Buenavista (Quindío)',                 'Quindío',                       0.5),
  ('Calarcá',                              'Quindío',                       0.5),
  ('Circasia',                             'Quindío',                       0.5),
  ('Córdoba (Quindío)',                    'Quindío',                       0.5),
  ('Filandia',                             'Quindío',                       0.5),
  ('Génova',                               'Quindío',                       0.5),
  ('La Tebaida',                           'Quindío',                       0.5),
  ('Montenegro',                           'Quindío',                       0.5),
  ('Pijao',                                'Quindío',                       0.5),
  ('Quimbaya',                             'Quindío',                       0.5),
  ('Salento',                              'Quindío',                       0.5),

  -- ── Risaralda ─────────────────────────────────────────────────────────
  ('Pereira',                              'Risaralda',                     0.5),
  ('Apía',                                 'Risaralda',                     0.5),
  ('Balboa (Risaralda)',                   'Risaralda',                     0.5),
  ('Belén de Umbría',                      'Risaralda',                     0.5),
  ('Dosquebradas',                         'Risaralda',                     0.5),
  ('Guática',                              'Risaralda',                     0.5),
  ('La Celia',                             'Risaralda',                     0.5),
  ('La Virginia',                          'Risaralda',                     0.5),
  ('Marsella',                             'Risaralda',                     0.5),
  ('Mistrató',                             'Risaralda',                     0.5),
  ('Pueblo Rico (Risaralda)',             'Risaralda',                     0.5),
  ('Quinchía',                             'Risaralda',                     0.5),
  ('Santa Rosa de Cabal',                  'Risaralda',                     0.5),
  ('Santuario',                            'Risaralda',                     0.5),

  -- ── San Andrés y Providencia ──────────────────────────────────────────
  ('San Andrés',                           'San Andrés y Providencia',      0.5),
  ('Providencia',                          'San Andrés y Providencia',      0.5),

  -- ── Santander ─────────────────────────────────────────────────────────
  ('Bucaramanga',                          'Santander',                     0.4),
  ('Aguada',                               'Santander',                     0.5),
  ('Albania (Santander)',                  'Santander',                     0.5),
  ('Aratoca',                              'Santander',                     0.5),
  ('Barbosa (Santander)',                  'Santander',                     0.5),
  ('Barichara',                            'Santander',                     0.5),
  ('Barrancabermeja',                      'Santander',                     0.5),
  ('Betulia (Santander)',                  'Santander',                     0.5),
  ('Bolívar (Santander)',                  'Santander',                     0.5),
  ('Cabrera (Santander)',                  'Santander',                     0.5),
  ('California (Santander)',               'Santander',                     0.5),
  ('Capitanejo',                           'Santander',                     0.5),
  ('Carcasí',                              'Santander',                     0.5),
  ('Cepitá',                               'Santander',                     0.5),
  ('Cerrito',                              'Santander',                     0.5),
  ('Charalá',                              'Santander',                     0.5),
  ('Charta',                               'Santander',                     0.5),
  ('Chima (Santander)',                    'Santander',                     0.5),
  ('Chipatá',                              'Santander',                     0.5),
  ('Cimitarra',                            'Santander',                     0.5),
  ('Confines',                             'Santander',                     0.5),
  ('Contratación',                         'Santander',                     0.5),
  ('Coromoro',                             'Santander',                     0.5),
  ('Curití',                               'Santander',                     0.5),
  ('El Carmen de Chucurí',                'Santander',                     0.5),
  ('El Guacamayo',                         'Santander',                     0.5),
  ('El Peñón (Santander)',                 'Santander',                     0.5),
  ('El Playón',                            'Santander',                     0.5),
  ('Encino',                               'Santander',                     0.5),
  ('Enciso',                               'Santander',                     0.5),
  ('Florián',                              'Santander',                     0.5),
  ('Floridablanca',                        'Santander',                     0.5),
  ('Galán',                                'Santander',                     0.5),
  ('Gámbita',                              'Santander',                     0.5),
  ('Girón',                                'Santander',                     0.5),
  ('Guaca',                                'Santander',                     0.5),
  ('Guadalupe (Santander)',                'Santander',                     0.5),
  ('Guapotá',                              'Santander',                     0.5),
  ('Guavatá',                              'Santander',                     0.5),
  ('Güepsa',                               'Santander',                     0.5),
  ('Hato',                                 'Santander',                     0.5),
  ('Jesús María',                          'Santander',                     0.5),
  ('Jordán',                               'Santander',                     0.5),
  ('La Belleza',                           'Santander',                     0.5),
  ('La Paz (Santander)',                   'Santander',                     0.5),
  ('Landázuri',                            'Santander',                     0.5),
  ('Lebrija',                              'Santander',                     0.5),
  ('Los Santos',                           'Santander',                     0.5),
  ('Macaravita',                           'Santander',                     0.5),
  ('Málaga',                               'Santander',                     0.5),
  ('Matanza',                              'Santander',                     0.5),
  ('Mogotes',                              'Santander',                     0.5),
  ('Molagavita',                           'Santander',                     0.5),
  ('Ocamonte',                             'Santander',                     0.5),
  ('Oiba',                                 'Santander',                     0.5),
  ('Onzaga',                               'Santander',                     0.5),
  ('Palmar (Santander)',                   'Santander',                     0.5),
  ('Palmas del Socorro',                   'Santander',                     0.5),
  ('Páramo',                               'Santander',                     0.5),
  ('Piedecuesta',                          'Santander',                     0.5),
  ('Pinchote',                             'Santander',                     0.5),
  ('Puente Nacional',                      'Santander',                     0.5),
  ('Puerto Parra',                         'Santander',                     0.5),
  ('Puerto Wilches',                       'Santander',                     0.5),
  ('Rionegro (Santander)',                 'Santander',                     0.5),
  ('Sabana de Torres',                     'Santander',                     0.5),
  ('San Andrés (Santander)',               'Santander',                     0.5),
  ('San Benito (Santander)',               'Santander',                     0.5),
  ('San Gil',                              'Santander',                     0.5),
  ('San Joaquín',                          'Santander',                     0.5),
  ('San José de Miranda',                  'Santander',                     0.5),
  ('San Miguel (Santander)',               'Santander',                     0.5),
  ('San Vicente de Chucurí',              'Santander',                     0.5),
  ('Santa Bárbara (Santander)',           'Santander',                     0.5),
  ('Santa Helena del Opón',               'Santander',                     0.5),
  ('Simacota',                             'Santander',                     0.5),
  ('Socorro',                              'Santander',                     0.5),
  ('Suaita',                               'Santander',                     0.5),
  ('Sucre (Santander)',                    'Santander',                     0.5),
  ('Suratá',                               'Santander',                     0.5),
  ('Tona',                                 'Santander',                     0.5),
  ('Valle de San José',                    'Santander',                     0.5),
  ('Vélez',                                'Santander',                     0.5),
  ('Vetas',                                'Santander',                     0.5),
  ('Villanueva (Santander)',               'Santander',                     0.5),
  ('Zapatoca',                             'Santander',                     0.5),

  -- ── Sucre ─────────────────────────────────────────────────────────────
  ('Sincelejo',                            'Sucre',                         0.5),
  ('Buenavista (Sucre)',                   'Sucre',                         0.5),
  ('Caimito',                              'Sucre',                         0.5),
  ('Chalán',                               'Sucre',                         0.5),
  ('Coloso',                               'Sucre',                         0.5),
  ('Corozal',                              'Sucre',                         0.5),
  ('Coveñas',                              'Sucre',                         0.5),
  ('El Roble (Sucre)',                     'Sucre',                         0.5),
  ('Galeras',                              'Sucre',                         0.5),
  ('Guaranda',                             'Sucre',                         0.5),
  ('La Unión (Sucre)',                     'Sucre',                         0.5),
  ('Los Palmitos',                         'Sucre',                         0.5),
  ('Majagual',                             'Sucre',                         0.5),
  ('Morroa',                               'Sucre',                         0.5),
  ('Ovejas',                               'Sucre',                         0.5),
  ('Palmito',                              'Sucre',                         0.5),
  ('Sampués',                              'Sucre',                         0.5),
  ('San Benito Abad',                      'Sucre',                         0.5),
  ('San Juan de Betulia',                  'Sucre',                         0.5),
  ('San Luis de Sincé',                    'Sucre',                         0.5),
  ('San Marcos',                           'Sucre',                         0.5),
  ('San Onofre',                           'Sucre',                         0.5),
  ('San Pedro (Sucre)',                    'Sucre',                         0.5),
  ('Santiago de Tolú',                     'Sucre',                         0.5),
  ('Sucre',                                'Sucre',                         0.5),
  ('Tolú Viejo',                           'Sucre',                         0.5),

  -- ── Tolima — todos los 47 municipios (incluye los del bug report) ──────
  ('Ibagué',                               'Tolima',                        0.5),
  ('Alpujarra',                            'Tolima',                        0.5),
  ('Alvarado',                             'Tolima',                        0.5),
  ('Ambalema',                             'Tolima',                        0.5),
  ('Anzoátegui (Tolima)',                 'Tolima',                        0.5),
  ('Armero',                               'Tolima',                        0.5),
  ('Ataco',                                'Tolima',                        0.5),
  ('Cajamarca',                            'Tolima',                        0.5),
  ('Carmen de Apicalá',                    'Tolima',                        0.5),
  ('Casabianca',                           'Tolima',                        0.5),
  ('Chaparral',                            'Tolima',                        0.5),
  ('Coello',                               'Tolima',                        0.5),
  ('Coyaima',                              'Tolima',                        0.5),
  ('Cunday',                               'Tolima',                        0.5),
  ('Dolores (Tolima)',                     'Tolima',                        0.5),
  ('El Espinal',                           'Tolima',                        0.5),
  ('Falan',                                'Tolima',                        0.5),
  ('Flandes',                              'Tolima',                        0.5),
  ('Fresno',                               'Tolima',                        0.5),
  ('Guamo',                                'Tolima',                        0.5),
  ('Herveo',                               'Tolima',                        0.5),
  ('Honda',                                'Tolima',                        0.5),
  ('Icononzo',                             'Tolima',                        0.5),
  ('Lérida',                               'Tolima',                        0.5),
  ('Líbano',                               'Tolima',                        0.5),
  ('Mariquita',                            'Tolima',                        0.5),
  ('Melgar',                               'Tolima',                        0.5),
  ('Murillo (Tolima)',                     'Tolima',                        0.5),
  ('Natagaima',                            'Tolima',                        0.5),
  ('Ortega',                               'Tolima',                        0.5),
  ('Palocabildo',                          'Tolima',                        0.5),
  ('Piedras (Tolima)',                     'Tolima',                        0.5),
  ('Planadas',                             'Tolima',                        0.5),
  ('Prado (Tolima)',                       'Tolima',                        0.5),
  ('Purificación',                         'Tolima',                        0.5),
  ('Rioblanco',                            'Tolima',                        0.5),
  ('Roncesvalles',                         'Tolima',                        0.5),
  ('Rovira',                               'Tolima',                        0.5),
  ('Saldaña',                              'Tolima',                        0.5),
  ('San Antonio (Tolima)',                 'Tolima',                        0.5),
  ('San Luis (Tolima)',                    'Tolima',                        0.5),
  ('Santa Isabel (Tolima)',                'Tolima',                        0.5),
  ('Suárez (Tolima)',                      'Tolima',                        0.5),
  ('Valle de San Juan',                    'Tolima',                        0.5),
  ('Venadillo',                            'Tolima',                        0.5),
  ('Villahermosa',                         'Tolima',                        0.5),
  ('Villarrica (Tolima)',                  'Tolima',                        0.5),

  -- ── Valle del Cauca ───────────────────────────────────────────────────
  ('Cali',                                 'Valle del Cauca',               0.5),
  ('Alcalá',                               'Valle del Cauca',               0.5),
  ('Andalucía',                            'Valle del Cauca',               0.5),
  ('Ansermanuevo',                         'Valle del Cauca',               0.5),
  ('Argelia (Valle)',                      'Valle del Cauca',               0.5),
  ('Bolívar (Valle)',                      'Valle del Cauca',               0.5),
  ('Buenaventura',                         'Valle del Cauca',               0.5),
  ('Buga',                                 'Valle del Cauca',               0.5),
  ('Bugalagrande',                         'Valle del Cauca',               0.5),
  ('Caicedonia',                           'Valle del Cauca',               0.5),
  ('Calima',                               'Valle del Cauca',               0.5),
  ('Candelaria (Valle)',                   'Valle del Cauca',               0.5),
  ('Cartago',                              'Valle del Cauca',               0.5),
  ('Dagua',                                'Valle del Cauca',               0.5),
  ('El Águila',                            'Valle del Cauca',               0.5),
  ('El Cairo',                             'Valle del Cauca',               0.5),
  ('El Cerrito',                           'Valle del Cauca',               0.5),
  ('El Dovio',                             'Valle del Cauca',               0.5),
  ('Florida (Valle)',                      'Valle del Cauca',               0.5),
  ('Ginebra',                              'Valle del Cauca',               0.5),
  ('Guacarí',                              'Valle del Cauca',               0.5),
  ('Jamundí',                              'Valle del Cauca',               0.5),
  ('La Cumbre',                            'Valle del Cauca',               0.5),
  ('La Unión (Valle)',                     'Valle del Cauca',               0.5),
  ('La Victoria (Valle)',                  'Valle del Cauca',               0.5),
  ('Obando',                               'Valle del Cauca',               0.5),
  ('Palmira',                              'Valle del Cauca',               0.5),
  ('Pradera',                              'Valle del Cauca',               0.5),
  ('Restrepo (Valle)',                     'Valle del Cauca',               0.5),
  ('Riofrío',                              'Valle del Cauca',               0.5),
  ('Roldanillo',                           'Valle del Cauca',               0.5),
  ('San Pedro (Valle)',                    'Valle del Cauca',               0.5),
  ('Sevilla',                              'Valle del Cauca',               0.5),
  ('Toro',                                 'Valle del Cauca',               0.5),
  ('Trujillo',                             'Valle del Cauca',               0.5),
  ('Tuluá',                                'Valle del Cauca',               0.5),
  ('Ulloa',                                'Valle del Cauca',               0.5),
  ('Versalles',                            'Valle del Cauca',               0.5),
  ('Vijes',                                'Valle del Cauca',               0.5),
  ('Yotoco',                               'Valle del Cauca',               0.5),
  ('Yumbo',                                'Valle del Cauca',               0.5),
  ('Zarzal',                               'Valle del Cauca',               0.5),

  -- ── Vaupés ────────────────────────────────────────────────────────────
  ('Mitú',                                 'Vaupés',                        0.5),
  ('Carurú',                               'Vaupés',                        0.5),
  ('Taraira',                              'Vaupés',                        0.5),

  -- ── Vichada ───────────────────────────────────────────────────────────
  ('Puerto Carreño',                       'Vichada',                       0.5),
  ('Cumaribo',                             'Vichada',                       0.5),
  ('La Primavera',                         'Vichada',                       0.5),
  ('Santa Rosalía',                        'Vichada',                       0.5)
)
INSERT INTO municipios (nombre, departamento, reteica_pct)
SELECT nombre, departamento, reteica_pct FROM source
ON CONFLICT (nombre) DO UPDATE
  SET departamento = EXCLUDED.departamento,
      reteica_pct  = EXCLUDED.reteica_pct;
